package com.watchme.roman.moviesgreendao.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.watchme.roman.moviesgreendao.model.Movie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVIE".
*/
public class MovieDao extends AbstractDao<Movie, Long> {

    public static final String TABLENAME = "MOVIE";

    /**
     * Properties of entity Movie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Movie_id = new Property(1, String.class, "movie_id", false, "MOVIE_ID");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property PosterURL = new Property(3, String.class, "posterURL", false, "POSTER_URL");
        public final static Property Release = new Property(4, Integer.class, "release", false, "RELEASE");
        public final static Property Tv = new Property(5, Boolean.class, "tv", false, "TV");
    };


    public MovieDao(DaoConfig config) {
        super(config);
    }
    
    public MovieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVIE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"MOVIE_ID\" TEXT," + // 1: movie_id
                "\"TITLE\" TEXT," + // 2: title
                "\"POSTER_URL\" TEXT," + // 3: posterURL
                "\"RELEASE\" INTEGER," + // 4: release
                "\"TV\" INTEGER);"); // 5: tv
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVIE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Movie entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String movie_id = entity.getMovie_id();
        if (movie_id != null) {
            stmt.bindString(2, movie_id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String posterURL = entity.getPosterURL();
        if (posterURL != null) {
            stmt.bindString(4, posterURL);
        }
 
        Integer release = entity.getRelease();
        if (release != null) {
            stmt.bindLong(5, release);
        }
 
        Boolean tv = entity.getTv();
        if (tv != null) {
            stmt.bindLong(6, tv ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Movie readEntity(Cursor cursor, int offset) {
        Movie entity = new Movie( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // movie_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // posterURL
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // release
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // tv
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Movie entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMovie_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPosterURL(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRelease(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setTv(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Movie entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Movie entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
